name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  animated_background: ^2.0.0

  google_fonts: ^6.2.1 # Updated Google Fonts dependency to the latest version
#  animated_background: ^2.0.0 # Added animated background dependency


  http: ^1.3.0 # Updated http dependency to resolve version conflict
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
